version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=hitpop2216
      - DB_NAME=guestbook
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hitpop2216
      MYSQL_DATABASE: guestbook
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
